--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigcrafter/KygekTagsShop
build-by-default: true
branches:
- main
projects:
  KygekTagsShop:
    path: ""
    libs:
    - src: Vecnavium/FormsUI/FormsUI
      version: ^1.1.2
    - src: thebigcrafter/Hydrogen/Hydrogen
      version: ^1.0.0
    - src: poggit/libasynql/libasynql
      version: ^4.2.0
...
